groups:
  - name: database_rules
    rules:
      - alert: DatabaseConnectionFailed
        expr: terrafusion_database_connected == 0
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database Connection Failed"
          description: "The application cannot connect to the database"
          
      - alert: DatabaseQuerySlowResponse
        expr: terrafusion_database_query_time_ms > 1000
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Slow Database Queries"
          description: "Database queries are taking more than 1 second to complete"
          
      - alert: DatabaseHighConnections
        expr: terrafusion_database_connections > 80
        for: 10m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High Database Connections"
          description: "There are {{ $value }} active database connections"
          
      - alert: DatabaseLowDiskSpace
        expr: terrafusion_database_disk_free_gb < 5
        for: 5m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Low Database Disk Space"
          description: "The database has only {{ $value }}GB free disk space remaining"
          
      - alert: DatabaseBackupFailure
        expr: terrafusion_database_backup_success == 0
        for: 24h
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database Backup Failure"
          description: "Database backup has failed for more than 24 hours"
          
      - alert: PostgreSQLHighCPU
        expr: terrafusion_postgres_cpu_usage > 80
        for: 15m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL High CPU Usage"
          description: "PostgreSQL is using {{ $value }}% CPU"
          
      - alert: PostgreSQLHighMemory
        expr: terrafusion_postgres_memory_usage > 85
        for: 15m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL High Memory Usage"
          description: "PostgreSQL is using {{ $value }}% memory"
          
      - alert: PostGISFunctionFailure
        expr: terrafusion_postgis_function_success == 0
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostGIS Function Failure"
          description: "A PostGIS database function has failed"