groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"
          dashboard_url: "http://grafana:3000/d/system-overview"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"
          dashboard_url: "http://grafana:3000/d/system-overview"

      - alert: CriticalMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 95% on {{ $labels.instance }}, system stability at risk"
          dashboard_url: "http://grafana:3000/d/system-overview"

      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 85% for more than 5 minutes on {{ $labels.instance }}: {{ $labels.mountpoint }}"
          dashboard_url: "http://grafana:3000/d/system-overview"

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute"
          dashboard_url: "http://grafana:3000/d/system-overview"

      - alert: SlowHTTPResponses
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance, handler)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow HTTP responses detected"
          description: "95th percentile of HTTP request duration is above 2 seconds for {{ $labels.handler }} on {{ $labels.instance }}"
          dashboard_url: "http://grafana:3000/d/system-overview"