global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/system_rules.yml"
  - "rules/database_rules.yml"
  - "rules/agent_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "terrafusion"
    static_configs:
      - targets: ["web:5000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "postgres"
    static_configs:
      - targets: ["db:5432"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: /metrics
    scrape_interval: 10s